//USER_TYPES
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";

//PRODUCT_TYPES
export const GET_PRODUCTS_BY_SELL = "GET_PRODUCTS_BY_SELL";
export const GET_PRODUCTS_BY_ARRIVAL = "GET_PRODUCTS_BY_ARRIVAL";

//LOADING


//ERRORS
export const SET_USER_ERROR = "SET_USER_ERROR";