//USER_TYPES
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const ADD_TO_CART = "ADD_TO_CART";


//PRODUCT_TYPES
export const GET_PRODUCTS_BY_SELL = "GET_PRODUCTS_BY_SELL";
export const GET_PRODUCTS_BY_ARRIVAL = "GET_PRODUCTS_BY_ARRIVAL";
export const GET_PRODUCTS_TO_SHOP = "GET_PRODUCTS_TO_SHOP";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const CLEAR_PRODUCT_DETAILS = "CLEAR_PRODUCT_DETAILS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";

//BRANDS
export const GET_BRANDS = "GET_BRANDS";
export const ADD_BRAND = "ADD_BRAND";

//WOODS
export const GET_WOODS = "GET_WOODS";
export const ADD_WOOD = "ADD_WOOD";

//LOADING


//ERRORS
export const SET_USER_ERROR = "SET_USER_ERROR";